### ISSUE TITLE
MULTI-Module Selection dropdown incorrect for RadioKing TX18S

### ISSUE THREAD

**Issue by pfeerick** [benlye/multi-downloads#5]
The firmware downloads page at https://downloads.multi-module.org/ is incorrectly showing the RadioKing TX18S as having a 5-in-1 MPM, whereas is it is actually a 4-in-1 (e.g. [MakerFire](https://shop.makerfire.com/products/radioking-tx18s-2-4g-hall-sensor-gimbal-opentx-remote-controller-type-c-charging-radio?aff=194)), and there is also a  RadioKing TX18S Lite, which only has the CC2500 (e.g. [Bangood](https://au.banggood.com/RadioKing-TX18S-or-Lite-Hall-Sensor-Gimbals-2_4G-16CH-Multi-protocol-RF-System-OpenTX-Transmitter-for-RC-Drone-p-1737196.html?cur_warehouse=CN&ID=424826294477)).

Just editing this for posterity / clarity: the RK TX18S ships with a PCB *marked* JP5IN1, but does not have the 915/867 Mhz submodule fitted underneath, making it a 4IN1. 

![image](https://user-images.githubusercontent.com/5500713/135230647-826bc015-5e68-4072-bf4a-7766ccdc8975.png)

**Comment by benlye** [comment]
Fixed TX18S and added TX18S Lite.

**Comment by pfeerick** [comment]
Thank you! :)
